const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let transactions=[];
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const toast=m=>{const t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.style.display='none',2500)};
async function api(path,opts){const r=await fetch(path,opts);if(!r.ok)throw new Error((await r.json()).error||'Request failed');return r.json()}
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const labels={monitor:'LIVE MONITOR',analyze:'RISK EXPLAINABILITY',graph:'FRAUD NETWORK',behavior:'BEHAVIORAL BASELINE'};$('#crumb').textContent=labels[page]||page.toUpperCase();window.scrollTo({top:0,behavior:'smooth'});if(page==='behavior')loadBehavior();if(page==='graph')loadGraph()}
$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
$('#newAnalysis').onclick=()=>go('analyze');
$('#refreshBtn').onclick=()=>loadMonitor();$('#reloadTable').onclick=()=>loadMonitor();
async function health(){try{const d=await api('/api/health');$('#apiStatus').textContent='API ONLINE · '+new Date(d.time).toLocaleTimeString();}catch(e){$('#apiStatus').textContent='API OFFLINE';}}
function row(t){const shift=t.previousLocation?`<b>${t.flags?.[0]||'Context shift'}</b><br><span class="muted">${t.previousLocation} → ${t.location}</span>`:t.previousDevice?`<b>Device mutation</b><br><span class="muted">${t.previousDevice} → ${t.device}</span>`:'<b>Baseline stable</b><br><span class="muted">'+t.location+'</span>';return `<tr><td><div class="txid">#${t.id}</div><div class="muted">Live stream</div></td><td><b>${money(t.amount)}</b><br><span class="muted">${t.recipient} (${t.recipientId})</span></td><td><span class="risk ${t.status}">● ${t.status.toUpperCase()} (${t.risk})</span></td><td>${shift}</td><td>${(t.flags||[]).map(f=>`<span class="tag">${f}</span>`).join('')||'<span class="muted">None</span>'}</td><td class="mini-actions"><button class="inspect" data-id="${t.id}">INSPECT</button>${t.risk>=55?'<button class="block">BLOCK</button>':'<button class="approve">APPROVE</button>'}</td></tr>`}
async function loadMonitor(){try{const d=await api('/api/transactions');transactions=d.transactions;$('#processed').textContent=money(d.processed24h);$('#critical').textContent=d.critical;$('#nodes').textContent=d.activeNodes.toLocaleString();$('#velocity').textContent=d.velocity+' tps';renderRows('all');const worst=Math.max(...transactions.map(x=>x.risk));$('#threatLabel').textContent=worst>=85?'ELEVATED':'NOMINAL';}catch(e){toast('Could not load live telemetry')}}
function renderRows(filter){const list=filter==='all'?transactions:transactions.filter(t=>t.status===filter);$('#txBody').innerHTML=list.map(row).join('');$$('.inspect').forEach(b=>b.onclick=()=>inspect(b.dataset.id));$$('.block').forEach(b=>b.onclick=()=>{b.textContent='BLOCKED';toast('Transaction blocked in demo mode')});$$('.approve').forEach(b=>b.onclick=()=>{b.textContent='APPROVED';toast('Transaction approved in demo mode')})}
function inspect(id){const t=transactions.find(x=>x.id===id);if(!t)return;go('analyze');const f=$('#analysisForm');f.amount.value=t.amount;f.recipient.value=t.recipient;f.recipientId.value=t.recipientId;f.device.value=t.device;f.location.value=t.location;f.qr.value=t.qr?'true':'false';f.velocity.value=t.velocity||1;f.message.value=t.message||'';f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));}
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRows(b.dataset.filter||'all')});
$('#analysisForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const payload=Object.fromEntries(f.entries());payload.amount=Number(payload.amount);payload.velocity=Number(payload.velocity);payload.qr=payload.qr==='true';$('#result').innerHTML='<div class="empty"><div>…</div><h2>Evaluating context</h2><p>Comparing payment against learned behavior, device, location and message signals.</p></div>';try{const d=await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderResult(d)}catch(err){toast(err.message)}});
function renderResult(d){const cls=d.label.toLowerCase();$('#result').innerHTML=`<div class="panel result-card"><p class="eyebrow">MODEL DECISION · ${d.transaction.id}</p><div class="score-row"><div class="score">${d.score}</div><div><span class="score-badge ${cls}">${d.label}</span><p style="margin:8px 0 0">Risk score out of 100</p></div></div><div class="meter"><i style="width:${d.score}%"></i></div><div class="action">Recommended action: ${d.action}</div><h2 style="margin-top:28px">Why this payment is unusual</h2>${d.reasons.map(r=>`<div class="reason"><div><b>${r.title}</b><span class="muted">${r.detail}</span></div><span class="weight">${r.weight>0?'+':''}${r.weight}</span></div>`).join('')}<h2 style="margin-top:25px">Learned baseline</h2><p>Average amount: <b>${money(d.baseline.average)}</b> · Standard deviation: <b>${money(d.baseline.stdDev)}</b> · Recipient payments: <b>${d.baseline.recipientPayments}</b> · Device known: <b>${d.baseline.knownDevice?'Yes':'No'}</b> · Location known: <b>${d.baseline.knownLocation?'Yes':'No'}</b></p></div>`}
async function loadBehavior(){const d=await api('/api/behavior');const max=Math.max(...d.history.map(x=>x.amount));$('#behaviorContent').innerHTML=`<div class="baseline-grid"><div class="baseline-card"><span>LEARNED AVERAGE</span><strong>${money(d.average)}</strong></div><div class="baseline-card"><span>MEDIAN</span><strong>${money(d.median)}</strong></div><div class="baseline-card"><span>STD. DEVIATION</span><strong>${money(d.stdDev)}</strong></div><div class="baseline-card"><span>COMMON DEVICE</span><strong style="font-size:21px">${d.typicalDevice}</strong></div></div><div class="panel"><div class="panel-title"><div><h2>Recent amount pattern</h2><p>Relative transaction size over the learned window</p></div></div><div class="bars">${d.history.slice().reverse().map(x=>`<div class="bar" style="height:${Math.max(10,x.amount/max*100)}%"><span>${(x.amount/1000).toFixed(1)}k</span></div>`).join('')}</div></div><div class="panel" style="margin-top:25px;padding:24px"><h2>Normal context</h2><p>Typical location: <b>${d.typicalLocation}</b> · Typical device: <b>${d.typicalDevice}</b></p><p>Top recipients: ${d.topRecipients.map(x=>`<span class="tag">${x.recipient} · ${x.count} payments</span>`).join(' ')}</p></div>`}
async function loadGraph(){const d=await api('/api/graph');$('#clusters').innerHTML=d.clusters.map(c=>`<div class="cluster"><b>${c.name}</b><p>${c.signal}</p><div class="riskline">NETWORK RISK · ${c.risk}/100</div><p>${c.members.join(' · ')}</p></div>`).join('');drawGraph(d)}
function drawGraph(d){const c=$('#graphCanvas'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),scale=window.devicePixelRatio||1;c.width=rect.width*scale;c.height=520*scale;ctx.setTransform(scale,0,0,scale,0,0);const w=rect.width,h=520;ctx.clearRect(0,0,w,h);ctx.font='10px DM Mono';const pos={ 'A-1042':[w*.18,120], 'A-7710':[w*.18,260], 'A-9921':[w*.18,400], 'A-2301':[w*.73,400], 'D-44':[w*.48,190], 'D-15':[w*.72,270], 'R-883':[w*.78,110], 'R-441':[w*.5,410]};ctx.setLineDash([5,6]);d.edges.forEach(e=>{const a=pos[e.source],b=pos[e.target];ctx.strokeStyle=e.risk>80?'rgba(255,89,100,.72)':'rgba(105,128,150,.55)';ctx.lineWidth=e.risk>80?2.4:1.4;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#63788e';ctx.font='9px DM Mono';ctx.fillText(e.label,(a[0]+b[0])/2+5,(a[1]+b[1])/2-5);ctx.setLineDash([5,6]);});ctx.setLineDash([]);d.nodes.forEach(n=>{const [x,y]=pos[n.id];const fill=n.risk>80?'#ff5964':n.risk>50?'#ffd45a':'#dce7ef';ctx.shadowColor=fill;ctx.shadowBlur=n.risk>80?18:7;ctx.fillStyle=fill;ctx.strokeStyle='#0a1522';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,25,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#07101c';ctx.font='700 9px DM Mono';ctx.textAlign='center';ctx.fillText(n.id,x,y+3);ctx.font='10px Inter';ctx.fillStyle='#8297aa';ctx.fillText(n.type,x,y+43);ctx.textAlign='left'});}
window.addEventListener('resize',()=>{if($('#graph').classList.contains('active'))loadGraph()});

loadMonitor();health();setInterval(loadMonitor,15000);
